
import PageLayout from "@/components/PageLayout";
import ClassCard from "@/components/ClassCard";
import { LectureType } from "@/types/lecture-types";
import MobileSearchBar from "@/components/MobileSearchBar";

const AcademicSubjects = () => {
  const classes = [
    {
      id: 1,
      className: "Advanced Mathematics",
      image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Algebra & Pre-Calculus Mastery Program",
      tutor: "Dr. Aisha Patel",
      rating: 4.9,
      reviewCount: 127,
      price: 1200,
      duration: 60,
      nextDate: "Tomorrow, 4:00 PM",
      tags: ["Math", "Ages 12-16"],
      isFeatured: true,
      lectureType: "live-group" as LectureType,
      classId: "algebra-precalculus-1",
      ageRange: "12-16",
    },
    {
      id: 2,
      className: "Science Explorer",
      image: "https://images.unsplash.com/photo-1532094349884-543bc11b234d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Fun with Chemistry: Experiments & Principles",
      tutor: "Prof. Rahul Sharma",
      rating: 4.8,
      reviewCount: 93,
      price: 1100,
      duration: 45,
      nextDate: "Saturday, 11:00 AM",
      tags: ["Science", "Ages 8-12"],
      lectureType: "live-one-on-one" as LectureType,
      classId: "chemistry-fun-1",
      ageRange: "8-12",
    },
    {
      id: 3,
      className: "Language Arts",
      image: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Creative Writing Workshop for Young Authors",
      tutor: "Ms. Priya Mehta",
      rating: 4.7,
      reviewCount: 85,
      price: 950,
      duration: 50,
      nextDate: "Monday, 5:30 PM",
      tags: ["English", "Ages 10-14"],
      lectureType: "recorded-on-demand" as LectureType,
      classId: "creative-writing-1",
      ageRange: "10-14",
    },
    {
      id: 4,
      className: "History & Social Studies",
      image: "https://images.unsplash.com/photo-1447069387593-a5de0862481e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Ancient Indian Civilizations: Stories & Artifacts",
      tutor: "Dr. Vikram Singh",
      rating: 4.9,
      reviewCount: 68,
      price: 1000,
      duration: 55,
      nextDate: "Wednesday, 4:00 PM",
      tags: ["History", "Ages 11-15"],
      lectureType: "live-group" as LectureType,
      classId: "ancient-indian-civ-1",
      ageRange: "11-15",
    },
    {
      id: 5,
      className: "Environmental Studies",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Climate Science for Young Environmentalists",
      tutor: "Dr. Ananya Desai",
      rating: 4.8,
      reviewCount: 72,
      price: 1150,
      duration: 60,
      nextDate: "Friday, 3:30 PM",
      tags: ["Science", "Ages 12-16"],
      lectureType: "offline-tutor-travels" as LectureType,
      classId: "climate-science-1",
      ageRange: "12-16",
    },
    {
      id: 6,
      className: "Physics Fundamentals",
      image: "https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Understanding Forces & Motion Through Games",
      tutor: "Prof. Rajesh Kapoor",
      rating: 4.7,
      reviewCount: 64,
      price: 1250,
      duration: 60,
      nextDate: "Thursday, 5:00 PM",
      tags: ["Physics", "Ages 13-16"],
      lectureType: "offline-student-travels" as LectureType,
      classId: "physics-forces-1",
      ageRange: "13-16",
    },
    {
      id: 7,
      className: "Biology",
      image: "https://images.unsplash.com/photo-1530210124550-912dc1381cb8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Human Body Systems: Interactive Biology",
      tutor: "Dr. Meera Reddy",
      rating: 4.9,
      reviewCount: 91,
      price: 1300,
      duration: 55,
      nextDate: "Saturday, 2:00 PM",
      tags: ["Science", "Ages 12-15"],
      lectureType: "recorded-on-demand" as LectureType,
      classId: "biology-interactive-1",
      ageRange: "12-15",
    },
    {
      id: 8,
      className: "Geometry",
      image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Geometry in Real World Applications",
      tutor: "Prof. Arjun Kumar",
      rating: 4.8,
      reviewCount: 78,
      price: 1100,
      duration: 50,
      nextDate: "Monday, 4:30 PM",
      tags: ["Math", "Ages 11-14"],
      lectureType: "live-group" as LectureType,
      classId: "geometry-real-world-1",
      ageRange: "11-14",
    },
    {
      id: 9,
      className: "Chemistry Advanced",
      image: "https://images.unsplash.com/photo-1603126857599-f6e157fa2fe6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Advanced Chemistry: Reactions & Compounds",
      tutor: "Dr. Sanjay Gupta",
      rating: 4.9,
      reviewCount: 65,
      price: 1400,
      duration: 60,
      nextDate: "Tuesday, 5:30 PM",
      tags: ["Science", "Ages 14-17"],
      lectureType: "offline-student-travels" as LectureType,
      classId: "advanced-chemistry-1",
      ageRange: "14-17",
    },
    {
      id: 10,
      className: "Literature Studies",
      image: "https://images.unsplash.com/photo-1474932430478-367dbb6832c1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "World Literature for Young Readers",
      tutor: "Ms. Anjali Singh",
      rating: 4.8,
      reviewCount: 87,
      price: 950,
      duration: 45,
      nextDate: "Wednesday, 3:00 PM",
      tags: ["Literature", "Ages 11-15"],
      lectureType: "live-one-on-one" as LectureType,
      classId: "world-literature-1",
      ageRange: "11-15",
    },
    {
      id: 11,
      className: "Geography",
      image: "https://images.unsplash.com/photo-1519338381761-c7523edc1f46?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "World Geography: Cultures & Landscapes",
      tutor: "Mr. Vikrant Khanna",
      rating: 4.7,
      reviewCount: 63,
      price: 1050,
      duration: 50,
      nextDate: "Thursday, 1:00 PM",
      tags: ["Geography", "Ages 10-14"],
      lectureType: "recorded-on-demand" as LectureType,
      classId: "world-geography-1",
      ageRange: "10-14",
    },
    {
      id: 12,
      className: "Economics",
      image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Introduction to Economics for Teens",
      tutor: "Prof. Ravi Kapoor",
      rating: 4.6,
      reviewCount: 54,
      price: 1200,
      duration: 55,
      nextDate: "Friday, 6:00 PM",
      tags: ["Economics", "Ages 13-17"],
      lectureType: "live-group" as LectureType,
      classId: "intro-economics-1",
      ageRange: "13-17",
    }
  ];

  return (
    <PageLayout
      title="Academic Subjects"
      description="Discover engaging classes in Math, Science, Language Arts, and more taught by expert educators for students of all ages."
    >
      <MobileSearchBar />
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {classes.map((classItem) => (
          <ClassCard key={classItem.id} {...classItem} />
        ))}
      </div>
    </PageLayout>
  );
};

export default AcademicSubjects;
