
import PageLayout from "@/components/PageLayout";
import ClassCard from "@/components/ClassCard";
import { LectureType } from "@/types/lecture-types";
import MobileSearchBar from "@/components/MobileSearchBar";

const ArtsCreativity = () => {
  const classes = [
    {
      id: 1,
      className: "Music & Instruments",
      image: "https://images.unsplash.com/photo-1514119412350-e174d90d280e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Beginner Violin: From Strings to Songs",
      tutor: "Ms. Priya Sharma",
      rating: 4.9,
      reviewCount: 124,
      price: 1500,
      duration: 45,
      nextDate: "Tomorrow, 4:00 PM",
      tags: ["Music", "Ages 7-12"],
      isFeatured: true,
      lectureType: "live-one-on-one" as LectureType,
      classId: "beginner-violin-1",
      ageRange: "7-12",
    },
    {
      id: 2,
      className: "Drawing & Painting",
      image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Watercolor Techniques for Beginners",
      tutor: "Ms. Anjali Khanna",
      rating: 4.8,
      reviewCount: 87,
      price: 1100,
      duration: 60,
      nextDate: "Saturday, 11:00 AM",
      tags: ["Art", "Ages 8-14"],
      lectureType: "live-group" as LectureType,
      classId: "watercolor-techniques-1",
    },
    {
      id: 3,
      className: "Drama & Theatre",
      image: "https://images.unsplash.com/photo-1503095396549-807759245b35?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Introduction to Acting: Expression & Confidence",
      tutor: "Mr. Rahul Verma",
      rating: 4.7,
      reviewCount: 72,
      price: 1200,
      duration: 60,
      nextDate: "Monday, 5:30 PM",
      tags: ["Drama", "Ages 10-16"],
      lectureType: "offline-tutor-travels" as LectureType,
      classId: "intro-acting-1",
    },
    {
      id: 4,
      className: "Vocal Music",
      image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Vocal Training: Finding Your Voice",
      tutor: "Ms. Shreya Patel",
      rating: 4.9,
      reviewCount: 95,
      price: 1300,
      duration: 45,
      nextDate: "Wednesday, 4:00 PM",
      tags: ["Singing", "Ages 9-15"],
      lectureType: "live-one-on-one" as LectureType,
      classId: "vocal-training-1",
    },
    {
      id: 5,
      className: "Digital Art",
      image: "https://images.unsplash.com/photo-1626785774573-4b799315345d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Digital Illustration for Young Artists",
      tutor: "Mr. Arjun Mathur",
      rating: 4.8,
      reviewCount: 68,
      price: 1400,
      duration: 60,
      nextDate: "Friday, 3:30 PM",
      tags: ["Digital", "Ages 12-16"],
      lectureType: "recorded-on-demand" as LectureType,
      classId: "digital-illustration-1",
    },
    {
      id: 6,
      className: "Dance",
      image: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Bharatanatyam: Classical Indian Dance for Beginners",
      tutor: "Ms. Lakshmi Krishnan",
      rating: 4.9,
      reviewCount: 102,
      price: 1250,
      duration: 60,
      nextDate: "Thursday, 5:00 PM",
      tags: ["Dance", "Ages 7-14"],
      lectureType: "offline-student-travels" as LectureType,
      classId: "bharatanatyam-1",
    },
    {
      id: 7,
      className: "Photography",
      image: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Digital Photography for Young Creators",
      tutor: "Mr. Vivek Malhotra",
      rating: 4.8,
      reviewCount: 83,
      price: 1350,
      duration: 65,
      nextDate: "Saturday, 3:00 PM",
      tags: ["Photo", "Ages 12-16"],
      lectureType: "live-group" as LectureType,
      classId: "digital-photography-1",
      ageRange: "12-16",
    },
    {
      id: 8,
      className: "Guitar",
      image: "https://images.unsplash.com/photo-1525201548942-d8732f6617a0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Beginner Guitar: Chords & Strumming Patterns",
      tutor: "Mr. Rohit Mehta",
      rating: 4.9,
      reviewCount: 116,
      price: 1450,
      duration: 50,
      nextDate: "Tuesday, 6:00 PM",
      tags: ["Music", "Ages 9-15"],
      lectureType: "live-one-on-one" as LectureType,
      classId: "beginner-guitar-1",
      ageRange: "9-15",
    },
    {
      id: 9,
      className: "Pottery & Ceramics",
      image: "https://images.unsplash.com/photo-1565373679107-224d47608fcb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Hands-on Pottery Workshop for Kids",
      tutor: "Ms. Aditi Sharma",
      rating: 4.7,
      reviewCount: 75,
      price: 1550,
      duration: 70,
      nextDate: "Sunday, 11:00 AM",
      tags: ["Craft", "Ages 8-14"],
      lectureType: "offline-student-travels" as LectureType,
      classId: "pottery-workshop-1",
      ageRange: "8-14",
    },
    {
      id: 10,
      className: "Animation",
      image: "https://images.unsplash.com/photo-1602529710584-458a995c8785?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "2D Animation for Young Storytellers",
      tutor: "Mr. Akash Gupta",
      rating: 4.8,
      reviewCount: 88,
      price: 1600,
      duration: 65,
      nextDate: "Monday, 4:30 PM",
      tags: ["Animation", "Ages 11-16"],
      lectureType: "recorded-on-demand" as LectureType,
      classId: "2d-animation-1",
      ageRange: "11-16",
    },
    {
      id: 11,
      className: "Creative Writing",
      image: "https://images.unsplash.com/photo-1455390582262-044cdead277a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Creative Storytelling & Fiction Writing",
      tutor: "Ms. Nisha Kapoor",
      rating: 4.9,
      reviewCount: 97,
      price: 1250,
      duration: 55,
      nextDate: "Wednesday, 5:30 PM",
      tags: ["Writing", "Ages 10-15"],
      lectureType: "live-group" as LectureType,
      classId: "creative-storytelling-1",
      ageRange: "10-15",
    },
    {
      id: 12,
      className: "Kathak Dance",
      image: "https://images.unsplash.com/photo-1535525153412-5a42439a210d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Kathak Dance: Classical Indian Footwork",
      tutor: "Ms. Radha Krishnan",
      rating: 4.8,
      reviewCount: 91,
      price: 1350,
      duration: 60,
      nextDate: "Thursday, 6:30 PM",
      tags: ["Dance", "Ages 8-16"],
      lectureType: "offline-tutor-travels" as LectureType,
      classId: "kathak-dance-1",
      ageRange: "8-16",
    }
  ];

  return (
    <PageLayout
      title="Arts & Creativity"
      description="Explore classes in music, visual arts, drama, dance, and creative expression taught by accomplished artists and educators."
    >
      <MobileSearchBar />
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {classes.map((classItem) => (
          <ClassCard key={classItem.id} {...classItem} />
        ))}
      </div>
    </PageLayout>
  );
};

export default ArtsCreativity;
