
import PageLayout from "@/components/PageLayout";
import ClassCard from "@/components/ClassCard";
import { LectureType } from "@/types/lecture-types";
import MobileSearchBar from "@/components/MobileSearchBar";

const LifeSkills = () => {
  const classes = [
    {
      id: 1,
      className: "Public Speaking",
      image: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Public Speaking & Confidence for Young Leaders",
      tutor: "Mrs. Sunita Sharma",
      rating: 4.9,
      reviewCount: 118,
      price: 1400,
      duration: 60,
      nextDate: "Tomorrow, 5:00 PM",
      tags: ["Speaking", "Ages 11-16"],
      isFeatured: true,
      lectureType: "live-group" as LectureType,
      classId: "public-speaking-1",
      ageRange: "11-16",
    },
    {
      id: 2,
      className: "Financial Literacy",
      image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Money Management for Teens: Saving & Planning",
      tutor: "Mr. Rajiv Kapoor",
      rating: 4.8,
      reviewCount: 86,
      price: 1200,
      duration: 60,
      nextDate: "Saturday, 11:00 AM",
      tags: ["Finance", "Ages 13-17"],
      lectureType: "live-one-on-one" as LectureType,
      classId: "money-management-1",
    },
    {
      id: 3,
      className: "Leadership",
      image: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Young Leaders: Developing Essential Skills",
      tutor: "Ms. Priya Mehta",
      rating: 4.9,
      reviewCount: 92,
      price: 1300,
      duration: 75,
      nextDate: "Monday, 5:30 PM",
      tags: ["Leadership", "Ages 12-16"],
      lectureType: "live-group" as LectureType,
      classId: "young-leaders-1",
    },
    {
      id: 4,
      className: "Critical Thinking",
      image: "https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Problem Solving & Critical Thinking Workshop",
      tutor: "Dr. Vikram Singh",
      rating: 4.7,
      reviewCount: 78,
      price: 1150,
      duration: 60,
      nextDate: "Wednesday, 4:00 PM",
      tags: ["Thinking", "Ages 10-15"],
      lectureType: "recorded-on-demand" as LectureType,
      classId: "critical-thinking-1",
    },
    {
      id: 5,
      className: "Emotional Intelligence",
      image: "https://images.unsplash.com/photo-1573511860302-28c524319d2a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Emotional Intelligence for Young Minds",
      tutor: "Dr. Ananya Desai",
      rating: 4.8,
      reviewCount: 85,
      price: 1250,
      duration: 60,
      nextDate: "Friday, 3:30 PM",
      tags: ["EQ", "Ages 8-14"],
      lectureType: "offline-tutor-travels" as LectureType,
      classId: "emotional-intelligence-1",
    },
    {
      id: 6,
      className: "Communication",
      image: "https://images.unsplash.com/photo-1552664730-d307ca884978?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Effective Communication Skills for Students",
      tutor: "Mr. Rahul Sharma",
      rating: 4.9,
      reviewCount: 103,
      price: 1300,
      duration: 60,
      nextDate: "Thursday, 5:00 PM",
      tags: ["Communication", "Ages 11-16"],
      lectureType: "live-one-on-one" as LectureType,
      classId: "communication-skills-1",
    },
    {
      id: 7,
      className: "Time Management",
      image: "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Time Management & Study Skills for Students",
      tutor: "Ms. Kavita Patel",
      rating: 4.7,
      reviewCount: 89,
      price: 1100,
      duration: 55,
      nextDate: "Tuesday, 5:00 PM",
      tags: ["Productivity", "Ages 12-17"],
      lectureType: "recorded-on-demand" as LectureType,
      classId: "time-management-1",
      ageRange: "12-17",
    },
    {
      id: 8,
      className: "Entrepreneurship",
      image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Young Entrepreneurs: Business Basics",
      tutor: "Mr. Ajay Mishra",
      rating: 4.9,
      reviewCount: 76,
      price: 1500,
      duration: 70,
      nextDate: "Saturday, 2:30 PM",
      tags: ["Business", "Ages 14-18"],
      lectureType: "live-group" as LectureType,
      classId: "young-entrepreneurs-1",
      ageRange: "14-18",
    },
    {
      id: 9,
      className: "Digital Citizenship",
      image: "https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Digital Citizenship & Online Safety",
      tutor: "Mrs. Neha Kumar",
      rating: 4.8,
      reviewCount: 82,
      price: 1200,
      duration: 60,
      nextDate: "Sunday, 11:00 AM",
      tags: ["Digital", "Ages 10-15"],
      lectureType: "live-group" as LectureType,
      classId: "digital-citizenship-1",
      ageRange: "10-15",
    },
    {
      id: 10,
      className: "Health & Wellness",
      image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Health, Nutrition & Wellness for Teens",
      tutor: "Dr. Alisha Reddy",
      rating: 4.9,
      reviewCount: 94,
      price: 1350,
      duration: 60,
      nextDate: "Monday, 6:00 PM",
      tags: ["Health", "Ages 13-17"],
      lectureType: "offline-tutor-travels" as LectureType,
      classId: "health-wellness-1",
      ageRange: "13-17",
    },
    {
      id: 11,
      className: "Conflict Resolution",
      image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Conflict Resolution & Peer Mediation",
      tutor: "Ms. Deepa Singh",
      rating: 4.7,
      reviewCount: 71,
      price: 1150,
      duration: 55,
      nextDate: "Wednesday, 3:30 PM",
      tags: ["Social", "Ages 11-16"],
      lectureType: "live-one-on-one" as LectureType,
      classId: "conflict-resolution-1",
      ageRange: "11-16",
    },
    {
      id: 12,
      className: "Mindfulness",
      image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Mindfulness & Stress Management for Students",
      tutor: "Dr. Maya Sharma",
      rating: 4.9,
      reviewCount: 105,
      price: 1250,
      duration: 50,
      nextDate: "Friday, 4:30 PM",
      tags: ["Wellness", "Ages 10-17"],
      lectureType: "recorded-on-demand" as LectureType,
      classId: "mindfulness-stress-1",
      ageRange: "10-17",
    }
  ];

  return (
    <PageLayout
      title="Life Skills"
      description="Discover classes in public speaking, financial literacy, leadership, and essential life skills for children and teenagers."
    >
      <MobileSearchBar />
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {classes.map((classItem) => (
          <ClassCard key={classItem.id} {...classItem} />
        ))}
      </div>
    </PageLayout>
  );
};

export default LifeSkills;
