
import PageLayout from "@/components/PageLayout";
import ClassCard from "@/components/ClassCard";
import { LectureType } from "@/types/lecture-types";
import MobileSearchBar from "@/components/MobileSearchBar";

const TechnologyCoding = () => {
  const classes = [
    {
      id: 1,
      className: "Coding",
      image: "https://images.unsplash.com/photo-1587620962725-abab7fe55159?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Python Programming for Young Inventors",
      tutor: "Dr. Arjun Mehta",
      rating: 4.9,
      reviewCount: 142,
      price: 1800,
      duration: 60,
      nextDate: "Tomorrow, 5:00 PM",
      tags: ["Coding", "Ages 12-16"],
      isFeatured: true,
      lectureType: "live-group" as LectureType,
      classId: "python-programming-1",
      ageRange: "12-16",
    },
    {
      id: 2,
      className: "Game Design",
      image: "https://images.unsplash.com/photo-1556438064-2d7646166914?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Create Your First Video Game with Scratch",
      tutor: "Mr. Vikram Singh",
      rating: 4.8,
      reviewCount: 98,
      price: 1400,
      duration: 60,
      nextDate: "Saturday, 10:00 AM",
      tags: ["Games", "Ages 8-13"],
      lectureType: "live-one-on-one" as LectureType,
      classId: "game-design-scratch-1",
    },
    {
      id: 3,
      className: "Robotics",
      image: "https://images.unsplash.com/photo-1561557944-6e7860d1a7eb?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Introduction to Robotics & Engineering",
      tutor: "Dr. Priya Sharma",
      rating: 4.9,
      reviewCount: 87,
      price: 2000,
      duration: 75,
      nextDate: "Monday, 5:30 PM",
      tags: ["Robotics", "Ages 10-15"],
      lectureType: "offline-student-travels" as LectureType,
      classId: "robotics-engineering-1",
    },
    {
      id: 4,
      className: "Web Development",
      image: "https://images.unsplash.com/photo-1547658719-da2b51169166?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "HTML & CSS: Build Your First Website",
      tutor: "Ms. Ananya Desai",
      rating: 4.7,
      reviewCount: 74,
      price: 1600,
      duration: 60,
      nextDate: "Wednesday, 4:00 PM",
      tags: ["Web", "Ages 13-16"],
      lectureType: "live-group" as LectureType,
      classId: "web-dev-html-css-1",
    },
    {
      id: 5,
      className: "App Development",
      image: "https://images.unsplash.com/photo-1551650975-87deedd944c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Mobile App Development for Teens",
      tutor: "Mr. Rahul Kapoor",
      rating: 4.8,
      reviewCount: 68,
      price: 1900,
      duration: 75,
      nextDate: "Friday, 3:30 PM",
      tags: ["App Dev", "Ages 14-18"],
      lectureType: "live-one-on-one" as LectureType,
      classId: "mobile-app-dev-1",
    },
    {
      id: 6,
      className: "Digital Media",
      image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Digital Content Creation for Young Creators",
      tutor: "Ms. Meera Shah",
      rating: 4.7,
      reviewCount: 92,
      price: 1500,
      duration: 60,
      nextDate: "Thursday, 5:00 PM",
      tags: ["Media", "Ages 12-16"],
      lectureType: "recorded-on-demand" as LectureType,
      classId: "digital-content-creation-1",
    },
    {
      id: 7,
      className: "Artificial Intelligence",
      image: "https://images.unsplash.com/photo-1677442135408-4724393288b4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Introduction to AI for Young Learners",
      tutor: "Dr. Sanjay Kumar",
      rating: 4.9,
      reviewCount: 104,
      price: 2200,
      duration: 65,
      nextDate: "Tuesday, 6:00 PM",
      tags: ["AI", "Ages 14-18"],
      lectureType: "live-group" as LectureType,
      classId: "intro-ai-1",
      ageRange: "14-18",
    },
    {
      id: 8,
      className: "Cybersecurity",
      image: "https://images.unsplash.com/photo-1553877522-43269d4ea984?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Cybersecurity Basics for Teens",
      tutor: "Mr. Rohan Verma",
      rating: 4.8,
      reviewCount: 78,
      price: 1700,
      duration: 60,
      nextDate: "Saturday, 2:00 PM",
      tags: ["Security", "Ages 13-17"],
      lectureType: "recorded-on-demand" as LectureType,
      classId: "cybersecurity-basics-1",
      ageRange: "13-17",
    },
    {
      id: 9,
      className: "3D Modeling",
      image: "https://images.unsplash.com/photo-1581553673739-c4906b5d0de8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "3D Modeling & Animation for Beginners",
      tutor: "Ms. Kavita Menon",
      rating: 4.7,
      reviewCount: 86,
      price: 1800,
      duration: 75,
      nextDate: "Wednesday, 5:30 PM",
      tags: ["3D", "Ages 12-16"],
      lectureType: "live-group" as LectureType,
      classId: "3d-modeling-1",
      ageRange: "12-16",
    },
    {
      id: 10,
      className: "Data Science",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Data Science Fundamentals for High Schoolers",
      tutor: "Dr. Amit Patel",
      rating: 4.9,
      reviewCount: 92,
      price: 2100,
      duration: 70,
      nextDate: "Monday, 4:30 PM",
      tags: ["Data", "Ages 15-18"],
      lectureType: "live-one-on-one" as LectureType,
      classId: "data-science-fundamentals-1",
      ageRange: "15-18",
    },
    {
      id: 11,
      className: "Minecraft Coding",
      image: "https://images.unsplash.com/photo-1623934199716-dc28818a6ec7?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Coding with Minecraft: Java Edition",
      tutor: "Mr. Karan Singh",
      rating: 4.8,
      reviewCount: 115,
      price: 1500,
      duration: 60,
      nextDate: "Friday, 4:00 PM",
      tags: ["Gaming", "Ages 10-15"],
      lectureType: "live-group" as LectureType,
      classId: "minecraft-java-1",
      ageRange: "10-15",
    },
    {
      id: 12,
      className: "Electronics",
      image: "https://images.unsplash.com/photo-1517420879524-86d64ac2f339?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      title: "Electronics & Circuit Design for Kids",
      tutor: "Dr. Ravi Shankar",
      rating: 4.7,
      reviewCount: 73,
      price: 1600,
      duration: 65,
      nextDate: "Thursday, 3:30 PM",
      tags: ["Electronics", "Ages 11-15"],
      lectureType: "offline-tutor-travels" as LectureType,
      classId: "electronics-circuits-1",
      ageRange: "11-15",
    }
  ];

  return (
    <PageLayout
      title="Technology & Coding"
      description="Explore classes in programming, game design, robotics, and digital skills taught by technology experts and educators."
    >
      <MobileSearchBar />
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {classes.map((classItem) => (
          <ClassCard key={classItem.id} {...classItem} />
        ))}
      </div>
    </PageLayout>
  );
};

export default TechnologyCoding;
