// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rrccjkygtyvfkroidwam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyY2Nqa3lndHl2Zmtyb2lkd2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAyNDczMDQsImV4cCI6MjA3NTgyMzMwNH0.uVwTdpyzUL9m7FNxzzV9yli256MyqT-XrY2pdGfTY88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});